import type { Task } from "./types";
export const tasks: Task[] = [
  {
    id: 1,
    title: "登录功能开发",
    description: "第1项示例任务：核对行为并补充验证。",
    status: "TODO",
    owner: "张三",
  },
  {
    id: 2,
    title: "任务列表接口对接",
    description: "第2项示例任务：核对行为并补充验证。",
    status: "DOING",
    owner: "李四",
  },
  {
    id: 3,
    title: "任务详情页面优化",
    description: "第3项示例任务：核对行为并补充验证。",
    status: "DONE",
    owner: "王五",
  },
  {
    id: 4,
    title: "筛选功能开发",
    description: "第4项示例任务：核对行为并补充验证。",
    status: "TODO",
    owner: "张三",
  },
  {
    id: 5,
    title: "任务状态更新",
    description: "第5项示例任务：核对行为并补充验证。",
    status: "DOING",
    owner: "李四",
  },
  {
    id: 6,
    title: "单元测试编写",
    description: "第6项示例任务：核对行为并补充验证。",
    status: "DONE",
    owner: "王五",
  },
  {
    id: 7,
    title: "登录输入校验",
    description: "第7项示例任务：核对行为并补充验证。",
    status: "TODO",
    owner: "张三",
  },
  {
    id: 8,
    title: "用户资料接口联调",
    description: "第8项示例任务：核对行为并补充验证。",
    status: "DOING",
    owner: "李四",
  },
  {
    id: 9,
    title: "分页交互优化",
    description: "第9项示例任务：核对行为并补充验证。",
    status: "DONE",
    owner: "王五",
  },
  {
    id: 10,
    title: "错误提示修正",
    description: "第10项示例任务：核对行为并补充验证。",
    status: "TODO",
    owner: "张三",
  },
  {
    id: 11,
    title: "移动端布局检查",
    description: "第11项示例任务：核对行为并补充验证。",
    status: "DOING",
    owner: "李四",
  },
  {
    id: 12,
    title: "组件样式整理",
    description: "第12项示例任务：核对行为并补充验证。",
    status: "DONE",
    owner: "王五",
  },
  {
    id: 13,
    title: "登录状态恢复",
    description: "第13项示例任务：核对行为并补充验证。",
    status: "TODO",
    owner: "张三",
  },
  {
    id: 14,
    title: "接口超时处理",
    description: "第14项示例任务：核对行为并补充验证。",
    status: "DOING",
    owner: "李四",
  },
  {
    id: 15,
    title: "任务列表空态",
    description: "第15项示例任务：核对行为并补充验证。",
    status: "DONE",
    owner: "王五",
  },
  {
    id: 16,
    title: "键盘导航检查",
    description: "第16项示例任务：核对行为并补充验证。",
    status: "TODO",
    owner: "张三",
  },
  {
    id: 17,
    title: "加载提示优化",
    description: "第17项示例任务：核对行为并补充验证。",
    status: "DOING",
    owner: "李四",
  },
  {
    id: 18,
    title: "前端构建检查",
    description: "第18项示例任务：核对行为并补充验证。",
    status: "DONE",
    owner: "王五",
  },
  {
    id: 19,
    title: "登录文案优化",
    description: "第19项示例任务：核对行为并补充验证。",
    status: "TODO",
    owner: "张三",
  },
  {
    id: 20,
    title: "接口权限回归",
    description: "第20项示例任务：核对行为并补充验证。",
    status: "DOING",
    owner: "李四",
  },
  {
    id: 21,
    title: "长标题换行",
    description: "第21项示例任务：核对行为并补充验证。",
    status: "DONE",
    owner: "王五",
  },
  {
    id: 22,
    title: "状态筛选回归",
    description: "第22项示例任务：核对行为并补充验证。",
    status: "TODO",
    owner: "张三",
  },
  {
    id: 23,
    title: "分页边界测试",
    description: "第23项示例任务：核对行为并补充验证。",
    status: "DOING",
    owner: "李四",
  },
  {
    id: 24,
    title: "交付文档整理",
    description: "第24项示例任务：核对行为并补充验证。",
    status: "DONE",
    owner: "王五",
  },
];
